//
// Created by Haidy on 2021/11/7.
//

#ifndef DOCKET_STATUS_H
#define DOCKET_STATUS_H

#define SOCKS_STATUS_WAIT_DISCONNECT -2
#define DOCKS_STATUS_NONE 0
#define DOCKS_STATUS_METHODS 1
#define DOCKS_STATUS_METHODS_RESPONSE 2
#define DOCKS_STATUS_AUTH 3
#define DOCKS_STATUS_AUTH_RESPONSE 4
#define DOCKS_STATUS_CONNECT 5
#define DOCKS_STATUS_DONE 6

#endif //DOCKET_STATUS_H
